PORT = YOUR_PORT_NUMBER

DATABASE = YOUR_MONGO_URL

SECRET_KEY = JWT_SECRET_KEY

AWS_REGION = YOUR_AWS_REGION

AWS_BUCKET_NAME = YOUR_AWS_BUCKET_NAME

AWS_ACCESS_KEY_ID = YOUR_AWS_ACCESS_KEY_ID

AWS_SECRET_ACCESS_KEY = YOUR_AWS_SECRET_ACCESS_KEY